### PR TITLE
Run prettier on project

### PR DESCRIPTION
**Pull request by cherewaty**
## Motivation
Sequel to https://github.com/resideo-platform/exemplar/pull/86

## Approach
Ran `yarn prettier`. It uses Prettier's default ruleset, without any modifications.

### CODE REVIEW

**Comment by cherewaty** [comment]
Added integration with ESLint. Here's a demonstrated failure: https://circleci.com/gh/resideo-platform/exemplar/4326

**Comment by cherewaty** [comment]
@taras do you have any specific rules you'd like to override? I figure if we're just using defaults (which I'm ok with for now), we don't need a `.prettierrc`.

**Comment by taras** [comment]
>  I figure if we're just using defaults (which I'm ok with for now), we don't need a .prettierrc.
As long as ESLint knows how to validate for prettier, then we should be fine.

**Comment by cherewaty** [comment]
Fixed the `ts-ignore`s that got moved around.

**Pull request merged**
